// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: internal/proto/lines.proto

package grpcserver

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line      []string `protobuf:"bytes,1,rep,name=line,proto3" json:"line,omitempty"`
	Frequency int32    `protobuf:"varint,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (x *LinesRequest) Reset() {
	*x = LinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_lines_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinesRequest) ProtoMessage() {}

func (x *LinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lines_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinesRequest.ProtoReflect.Descriptor instead.
func (*LinesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_lines_proto_rawDescGZIP(), []int{0}
}

func (x *LinesRequest) GetLine() []string {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *LinesRequest) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type LinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp []*LineDelta `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp,omitempty"`
}

func (x *LinesResponse) Reset() {
	*x = LinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_lines_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinesResponse) ProtoMessage() {}

func (x *LinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lines_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinesResponse.ProtoReflect.Descriptor instead.
func (*LinesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_lines_proto_rawDescGZIP(), []int{1}
}

func (x *LinesResponse) GetResp() []*LineDelta {
	if x != nil {
		return x.Resp
	}
	return nil
}

type LineDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line  string  `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Delta float64 `protobuf:"fixed64,2,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *LineDelta) Reset() {
	*x = LineDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_lines_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineDelta) ProtoMessage() {}

func (x *LineDelta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lines_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineDelta.ProtoReflect.Descriptor instead.
func (*LineDelta) Descriptor() ([]byte, []int) {
	return file_internal_proto_lines_proto_rawDescGZIP(), []int{2}
}

func (x *LineDelta) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LineDelta) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

var File_internal_proto_lines_proto protoreflect.FileDescriptor

var file_internal_proto_lines_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x40, 0x0a, 0x0c, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x22, 0x34, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x44,
	0x65, 0x6c, 0x74, 0x61, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x35, 0x0a, 0x09, 0x4c, 0x69,
	0x6e, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x32, 0x50, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x16, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x6e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x4c,
	0x69, 0x6e, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_lines_proto_rawDescOnce sync.Once
	file_internal_proto_lines_proto_rawDescData = file_internal_proto_lines_proto_rawDesc
)

func file_internal_proto_lines_proto_rawDescGZIP() []byte {
	file_internal_proto_lines_proto_rawDescOnce.Do(func() {
		file_internal_proto_lines_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_lines_proto_rawDescData)
	})
	return file_internal_proto_lines_proto_rawDescData
}

var file_internal_proto_lines_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_lines_proto_goTypes = []interface{}{
	(*LinesRequest)(nil),  // 0: main.LinesRequest
	(*LinesResponse)(nil), // 1: main.LinesResponse
	(*LineDelta)(nil),     // 2: main.LineDelta
}
var file_internal_proto_lines_proto_depIdxs = []int32{
	2, // 0: main.LinesResponse.resp:type_name -> main.LineDelta
	0, // 1: main.Lines.SubscribeOnSportsLines:input_type -> main.LinesRequest
	1, // 2: main.Lines.SubscribeOnSportsLines:output_type -> main.LinesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_lines_proto_init() }
func file_internal_proto_lines_proto_init() {
	if File_internal_proto_lines_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_lines_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_lines_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_lines_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_lines_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_lines_proto_goTypes,
		DependencyIndexes: file_internal_proto_lines_proto_depIdxs,
		MessageInfos:      file_internal_proto_lines_proto_msgTypes,
	}.Build()
	File_internal_proto_lines_proto = out.File
	file_internal_proto_lines_proto_rawDesc = nil
	file_internal_proto_lines_proto_goTypes = nil
	file_internal_proto_lines_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LinesClient is the client API for Lines service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LinesClient interface {
	SubscribeOnSportsLines(ctx context.Context, opts ...grpc.CallOption) (Lines_SubscribeOnSportsLinesClient, error)
}

type linesClient struct {
	cc grpc.ClientConnInterface
}

func NewLinesClient(cc grpc.ClientConnInterface) LinesClient {
	return &linesClient{cc}
}

func (c *linesClient) SubscribeOnSportsLines(ctx context.Context, opts ...grpc.CallOption) (Lines_SubscribeOnSportsLinesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Lines_serviceDesc.Streams[0], "/main.Lines/SubscribeOnSportsLines", opts...)
	if err != nil {
		return nil, err
	}
	x := &linesSubscribeOnSportsLinesClient{stream}
	return x, nil
}

type Lines_SubscribeOnSportsLinesClient interface {
	Send(*LinesRequest) error
	Recv() (*LinesResponse, error)
	grpc.ClientStream
}

type linesSubscribeOnSportsLinesClient struct {
	grpc.ClientStream
}

func (x *linesSubscribeOnSportsLinesClient) Send(m *LinesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *linesSubscribeOnSportsLinesClient) Recv() (*LinesResponse, error) {
	m := new(LinesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LinesServer is the server API for Lines service.
type LinesServer interface {
	SubscribeOnSportsLines(Lines_SubscribeOnSportsLinesServer) error
}

// UnimplementedLinesServer can be embedded to have forward compatible implementations.
type UnimplementedLinesServer struct {
}

func (*UnimplementedLinesServer) SubscribeOnSportsLines(Lines_SubscribeOnSportsLinesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOnSportsLines not implemented")
}

func RegisterLinesServer(s *grpc.Server, srv LinesServer) {
	s.RegisterService(&_Lines_serviceDesc, srv)
}

func _Lines_SubscribeOnSportsLines_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LinesServer).SubscribeOnSportsLines(&linesSubscribeOnSportsLinesServer{stream})
}

type Lines_SubscribeOnSportsLinesServer interface {
	Send(*LinesResponse) error
	Recv() (*LinesRequest, error)
	grpc.ServerStream
}

type linesSubscribeOnSportsLinesServer struct {
	grpc.ServerStream
}

func (x *linesSubscribeOnSportsLinesServer) Send(m *LinesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *linesSubscribeOnSportsLinesServer) Recv() (*LinesRequest, error) {
	m := new(LinesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Lines_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Lines",
	HandlerType: (*LinesServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOnSportsLines",
			Handler:       _Lines_SubscribeOnSportsLines_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/lines.proto",
}
